apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      project: wordpress
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        project: wordpress
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: MYSQL_USER
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress
