apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      project: wordpress
      app: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        project: wordpress
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql